# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  # The command to build the application.
  cmd = "go build -o ./tmp/main ./cmd/server"
  # The binary to run.
  bin = "./tmp/main"
  # Watch these file extensions.
  include_ext = ["go", "tpl", "tmpl", "html", "sql"]
  # Ignore these directories.
  exclude_dir = ["assets", "tmp", "vendor", "frontend", "db/migrations_old"]
  # Log file for build errors.
  log = "air-build-errors.log"
  # Delay between build and run.
  delay = 1000 # ms

[log]
  # Show log time
  time = true

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true